# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_auto_20161204_2059'),
        ('GroupsApp', '0005_auto_20161204_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_platforms',
        ),
        migrations.AddField(
            model_name='group',
            name='group_platform',
            field=models.ManyToManyField(to='AuthenticationApp.Skill'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_skills',
        ),
        migrations.AddField(
            model_name='group',
            name='group_skills',
            field=models.ManyToManyField(to='AuthenticationApp.Platform'),
        ),
    ]
