# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0006_auto_20161204_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_platform',
            field=models.ManyToManyField(to='AuthenticationApp.Platform'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_skills',
            field=models.ManyToManyField(to='AuthenticationApp.Skill'),
        ),
    ]
