# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0004_comment_creator'),
        ('GroupsApp', '0009_auto_20161205_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(to='CommentsApp.Comment'),
        ),
    ]
