# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0004_auto_20161126_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='members',
            new_name='bookmark',
        ),
    ]
