# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0018_auto_20161204_2059'),
        ('ProjectsApp', '0007_auto_20161202_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_platform',
            field=models.ManyToManyField(to='AuthenticationApp.Platform'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_skill',
            field=models.ManyToManyField(to='AuthenticationApp.Skill'),
        ),
    ]
