# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0021_auto_20161206_1646'),
        ('ProjectsApp', '0008_auto_20161204_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AuthenticationApp.Engineer'),
        ),
    ]
