# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_auto_20161123_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
