# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0007_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
