# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_auto_20161126_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='engineer',
            name='position',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='teachClass',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
