# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0009_auto_20161201_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='company',
        ),
    ]
