# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_teachclass'),
        ('AuthenticationApp', '0009_auto_20161201_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='teachClass',
        ),
        migrations.AddField(
            model_name='professor',
            name='teachClass',
            field=models.ManyToManyField(to='TeacherApp.TeachClass'),
        ),
    ]
