# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_remove_engineer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
