# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=1000)),
                ('skill', models.ManyToManyField(to='AuthenticationApp.Student')),
            ],
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='user',
            new_name='student',
        ),
    ]
