# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0014_auto_20161204_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
    ]
