# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0016_auto_20161204_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='platform',
            new_name='skill',
        ),
    ]
