# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0017_auto_20161204_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='student',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='platform',
            field=models.ManyToManyField(to='AuthenticationApp.Platform'),
        ),
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.ManyToManyField(to='AuthenticationApp.Skill'),
        ),
    ]
