# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_auto_20161202_0451'),
        ('AuthenticationApp', '0018_auto_20161204_2059'),
    ]

    operations = [
    ]
