# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_auto_20161111_1431'),
        ('AuthenticationApp', '0021_auto_20161206_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='company',
        ),
        migrations.AddField(
            model_name='engineer',
            name='company',
            field=models.ManyToManyField(to='CompaniesApp.Company'),
        ),
    ]
