# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_auto_20161202_0451'),
        ('TeacherApp', '0002_teachclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachclass',
            name='students',
            field=models.ManyToManyField(to='AuthenticationApp.Student'),
        ),
    ]
